drop schema if exists webproject
    cascade;
create schema webproject;
set search_path = webproject;

drop table if exists users;

Create table users(
    id int generated by default as identity ,
    username varchar(100) not null,
    password varchar(80) not null,
    id_role int,
    fullname varchar(100) ,
    quantityroutine int,
    quantityfollower int,
    quantityfollowed int,
    bio varchar(1000),
    sex varchar(10),
    age int,
    primary key (id)
);


create table routine(
    id int generated by default as identity ,
    name varchar(100) not null,
    duration time,
    volumn real,
    id_owner int references users(id),
    like_number int,
    comment_number int,
    image varchar(100),
    primary key (id),
    constraint fk_owner foreign key (id_owner) references users(id)
                    on delete no action on update no action
);

drop table if exists exercise cascade ;

create table exercise(
    id int generated by default as identity,
    name varchar(100) not null,
    description varchar(1000) not null,
    detail varchar(10000) not null ,
    equipment varchar(30),
    primary_muscle varchar(30),
    image varchar(100),
    primary key (id)
);

drop table if exists comment cascade ;

create table comment(
    id int generated by default as identity,
    description varchar(100),
    writerId int,
    routineId int,
    primary key (id),
    constraint fk_writer foreign key (writerId) references users(id)
                    on delete no action on update no action,
    constraint fk_locatation foreign key (routineId) references routine(id)
                    on delete no action on update no action

);


create table role(
    id int generated by default as identity ,
    name varchar(100) not null,
    primary key (id)
);

create table routine_exercise(
    id_routine int not null,
    id_exercise int not null,
    primary key (id_exercise,id_routine),

    constraint fk_routine foreign key (id_routine) references routine(id)
                             on delete no action on update no action ,
    constraint fk_exercise foreign key (id_exercise) references exercise(id) on delete no action on update no action
);

create table routine_comment(
    id_routine int not null ,
    id_comment int not null,
    primary key (id_routine,id_comment),

    constraint fk_routine1 foreign key (id_routine) references routine(id)
                            on delete no action on update no action,
    constraint fk_comment foreign key (id_comment) references comment(id)
                            on delete no action on update no action

);

insert into role(name) values ('ROLE_USER'),('ROLE_ADMIN');

insert into routine(name, duration, volumn, like_number, comment_number) values ('Home Transformation','00:30:00',1.3231,0,0);

insert into routine(name, duration, volumn,id_owner, like_number, comment_number) values ('Pull up hell','00:30:00',1,1.3231,0,0);

insert into routine(name, duration, volumn,id_owner, like_number, comment_number) values ('Push up hell','00:30:00',1,1.3231,0,0);

insert into exercise(name, description, equipment,primary_muscle,detail,image) VALUES ('Bench Press','Align your feet right below you knees. Squeeze your shoulder baldes together. Lift the bar in a straight trajectory.','Barbell','Chest','Lie flat on your back on a bench.
              Grip the bar with hands just wider than shoulder-width apart, so when you’re at the bottom of your move your hands are directly above your elbows. This allows for maximum force generation.
              Bring the bar slowly down to your chest as you breathe in.
              Push up as you breathe out, gripping the bar hard and watching a spot on the ceiling rather than the bar, so you can ensure it travels the same path every time.','/Images%20exercises/img.png');

insert into exercise(name, description, equipment,primary_muscle,detail,image) VALUES ('Bent Over Row','Squeeze your abdominal muscles. Spread yout weight evenly under your big toe, little toe and heel.','Barbell','Upper Back','Lie flat on your back on a bench.
              Grip the bar with hands just wider than shoulder-width apart, so when you’re at the bottom of your move your hands are directly above your elbows. This allows for maximum force generation.
              Bring the bar slowly down to your chest as you breathe in.
              Push up as you breathe out, gripping the bar hard and watching a spot on the ceiling rather than the bar, so you can ensure it travels the same path every time.','/Images%20exercises/img_1.png');

insert into exercise(name, description, equipment,primary_muscle,detail,image) VALUES ('Squat','Squeeze your abdominal muscles. Spread yout weight evenly under you big toe, little toe and heel.','Barbell','Quadriceps','Lie flat on your back on a bench.
              Grip the bar with hands just wider than shoulder-width apart, so when you’re at the bottom of your move your hands are directly above your elbows. This allows for maximum force generation.
              Bring the bar slowly down to your chest as you breathe in.
              Push up as you breathe out, gripping the bar hard and watching a spot on the ceiling rather than the bar, so you can ensure it travels the same path every time.','/Images%20exercises/img_2.png');

create table linkusers(
    id int generated by default as identity ,
    id_follower int not null ,
    id_followed int not null ,
    primary key (id)
);

delete from comment where id = 23;